[package]
name = "videos_processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqprs = "1.6.0"
async-trait = "0.1.80"
json = "0.12.4"
tokio = "1.37.0"
tracing-subscriber = "0.3.18"
