FROM python:3.11.4-slim

WORKDIR /videos_processor

COPY requirements.txt .

RUN apt-get update
RUN apt-get -y install ffmpeg libsm6 libxext6

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "-m", "src.processor"]
